django_crud/apps/urls.py
from django.urls import include, path
from django.contrib import admin


app_name = "crud"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls', namespace='crud')),
]

django_crud/crud/urls.py
from django.urls import path

from crud import views

app_name = 'crud'

urlpatterns = [
  path('', views.book_list, name='book_list'),
  path('new', views.book_create, name='book_new'),
  path('edit/<int:pk>', views.book_update, name='book_edit'),
  path('delete/<int:pk>', views.book_delete, name='book_delete'),
]

django_crud/crud/models.py
from django.db import models
from django.urls import reverse
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


from crud.choice import *


class Book(models.Model):
    name = models.CharField(max_length=200,)
    author = models.CharField(max_length=50)
    price = models.IntegerField()
    publish_year = models.IntegerField()
    pages = models.IntegerField()
    # status = models.CharField(max_length=20)
    status = models.CharField(choices=book_status,max_length=20, default='Available')


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('CRUD:book_edit', kwargs={'pk': self.pk})

    #year validation
    def validate_year(self):
        if self.publish_year < 1990 and self.publish_year > 2018:
            raise ValidationError(
                _('%(publish_year) Not a Valid Year  1990 - 2018'),
                params={'publish_year': publish_year},
            )

django_crud/apps/views.py
from django.shortcuts import render

django_crud/crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from crud.models import Book


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'author', 'pages', 'price', 'publish_year', 'status']


def book_list(request):
    book = Book.objects.all()
    data = {}
    data['object_list'] = book
    return render(request, 'books/book_list.html', data)


def book_create(request):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('crud:book_list')
    return render(request, 'books/book_form.html', {'form':form})


def book_update(request, pk):
    book= get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('crud:book_list')
    return render(request, 'books/book_form.html', {'form':form})

def book_delete(request, pk):
    book= get_object_or_404(Book, pk=pk)
    book.delete()
    return redirect('crud:book_list')

django_crud/crud/templates/books/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body>
{% block content %}
<!--<center>-->
<td><a href="{% url 'crud:book_list'%}">Home</a></td>
<form method="post">{% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Submit" />
</form>
<!--</center>-->
{% endblock %}
</body>
</html>

django_crud/crud/templates/books/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List Books</title>
    <style>
table, th, td
{
border: 1px solid black;
border-collapse: collapse;
    }
th, td {
    padding: 15px;
    text-align: left;
}
  </style>
</head>


<body>

{% block content %}

<h2><a href="{% url 'crud:book_new' %}">Create New Book</a></h2>

<table style="width:100%">
    <caption><h1>List of Books</h1></caption>
    <tr>
        <th><center>Book Name</center></th>
        <th><center>Author</center></th>
        <th><center>Publish Year</center></th>
        <th><center>Total Pages</center></th>
        <th><center>Price</center></th>
        <th><center>Status</center></th>
        <th><center>Update</center></th>
        <th><center>Delete</center></th>
    </tr>

    {% for book in object_list %}
    <tr>
        <td><center>{{ book.name }}</center></td>
        <td><center>{{book.author}}</center></td>
        <td><center>{{book.publish_year}}</center></td>
        <td><center>{{book.pages }}</center></td>
        <td><center>{{book.price}}</center></td>
        <td><center>{{book.status}}</center></td>
        <td><center><a href="{% url 'crud:book_edit' book.id %}" >Edit</a></center></td>
        <td><center><a href="{% url 'crud:book_delete' book.id %}" onclick="return confirm('You are About to Delete {{ book.name }}');">Delete</a></center></td>
    </tr>
    {% endfor %}
</table>


{% endblock %}
</body>
</html>